name: Build

on:
  push:
  pull_request:
  workflow_dispatch:
  repository_dispatch:
    types:
      - docs-update
  schedule:
    - cron: '0 06 * * *'

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true


jobs:
  calculate-version:
    name: Calculate Version
    runs-on: ubuntu-latest
    outputs:
      semVer: ${{ steps.gitversion.outputs.fullSemVer }}
    steps:
      - uses: actions/checkout@v3
        name: Checkout code
        with:
          fetch-depth: 0

      - uses: gittools/actions/gitversion/setup@v0.9.7
        name: Install GitVersion
        with:
          versionSpec: '5.x'

      - uses: gittools/actions/gitversion/execute@v0.9.7
        name: Determine Version
        id: gitversion
        with:
          useConfigFile: true
          configFilePath: gitversion.yml

  docsfinder_build:
    name: Build docsfinder
    runs-on: ubuntu-latest
    needs: 
      - calculate-version
    steps:
      - uses: actions/checkout@v3
        name: Checkout code

      - uses: actions/setup-go@v3
        name: Install Go
        with:
          go-version: '>=1.18.0'

      - name: Build project
        run: |
          cd docsfinder
          go build
      - uses: actions/upload-artifact@v3
        name: Upload artifact
        with:
          name: docsfinder-${{ needs.calculate-version.outputs.semVer }}-linux
          path: docsfinder

  site_build:
    name: Build site
    runs-on: ubuntu-latest
    needs: 
      - calculate-version
      - docsfinder_build
    steps:
      - uses: actions/checkout@v3
        name: Checkout code

      - uses: actions/download-artifact@v3
        with:
          name: docsfinder-${{ needs.calculate-version.outputs.semVer }}-linux
          path: ${{ github.workspace }}/tools
      
      - name: Make docsfinder executeable
        run: chmod +x ${{ github.workspace }}/tools/docsfinder

      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
          architecture: x64

      - name: Install MkDocs
        run: pip install -r mkdocs/requirements.txt

      - name: Make Readme.md homepage
        run: cp ${{ github.workspace }}/Readme.md ${{ github.workspace }}/mkdocs/docs/index.md

      - name: Docsfinder download
        run: > 
          ${{ github.workspace }}/tools/docsfinder
          --token ${{ secrets.DOCKER_DISPATCH_TOKEN }}
          --account rbjoergensen
          --exclude docs.callofthevoid.dk
          --output mkdocs/docs/github
          --mkdocs-config mkdocs/mkdocs.yml

      - name: Build MkDocs site
        run: |
          cd ${{ github.workspace }}/mkdocs
          mkdocs build

      - uses: actions/upload-artifact@v3
        name: Upload artifact
        with:
          name: site_${{ needs.calculate-version.outputs.semVer }}
          path: ${{ github.workspace }}/mkdocs/site/

  docker_build:
    name: Build Docker image
    runs-on: ubuntu-latest
    needs: 
      - calculate-version
      - site_build
    steps:
      - uses: actions/checkout@v3
        name: Checkout code

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: rbjoergensen
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/download-artifact@v3
        with:
          name: site_${{ needs.calculate-version.outputs.semVer }}
          path: ${{ github.workspace }}/site
      
      - name: debug currentdir
        run: ls -la
          
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            docker.pkg.github.com/rbjoergensen/docs.callofthevoid.dk/docs.callofthevoid.dk:latest,
            docker.pkg.github.com/rbjoergensen/docs.callofthevoid.dk/docs.callofthevoid.dk:${{ needs.calculate-version.outputs.semVer }}
          context: ${{ github.workspace }}

      - name: Repository dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.DOCKER_DISPATCH_TOKEN }}
          repository: rbjoergensen/home-server
          event-type: docker-build

  tag:
    name: Tag
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    needs: 
      - calculate-version
      - docker_build
    steps:
      - uses: actions/checkout@v3
        name: Checkout code

      - name: Create tag
        run: |
          git tag ${{ needs.calculate-version.outputs.semVer }}
          git push origin ${{ needs.calculate-version.outputs.semVer }}
