# https://www.mkdocs.org/user-guide/configuration/#documentation-layout
site_name: CallOfTheVoid
site_url: https://docs.callofthevoid.dk
repo_url: https://github.com/rbjoergensen
edit_uri: ""
# Third-party themes at https://github.com/mkdocs/mkdocs/wiki/MkDocs-Themes
theme: material # https://github.com/squidfunk/mkdocs-material
nav:
  - '<b>Introduction</b>': 'index.md'
  - '<b>Articles</b>': 
    - 'Awesome Sauce': 'articles/awesomesauce.md'
  - '<b>GitHub</b>':
    - '<b>ado-tokens</b>':
      - 'Readme.md': 'github/ado-tokens/Readme.md'
      - '<span style="font-style: italic;">Link(GitHub)</span>': 'https://github.com/rbjoergensen/ado-tokens'
    - '<b>appdynamics-integration-poc</b>':
      - 'Readme.md': 'github/appdynamics-integration-poc/Readme.md'
      - '<span style="font-style: italic;">Link(GitHub)</span>': 'https://github.com/rbjoergensen/appdynamics-integration-poc'
    - '<b>argo-test-app</b>':
      - 'Readme.md': 'github/argo-test-app/Readme.md'
      - '<span style="font-style: italic;">Link(GitHub)</span>': 'https://github.com/rbjoergensen/argo-test-app'
    - '<b>devops-articles</b>':
      - 'README.md': 'github/devops-articles/README.md'
      - '<span style="font-style: italic;">Link(GitHub)</span>': 'https://github.com/rbjoergensen/devops-articles'
    - '<b>infrastructure</b>':
      - 'Readme.md': 'github/infrastructure/Readme.md'
      - '<span style="font-style: italic;">Link(GitHub)</span>': 'https://github.com/rbjoergensen/infrastructure'
    - '<b>publish-pwsh-module</b>':
      - 'README.md': 'github/publish-pwsh-module/README.md'
      - '<span style="font-style: italic;">Link(GitHub)</span>': 'https://github.com/rbjoergensen/publish-pwsh-module'
    - '<b>tf-s3-bucket</b>':
      - 'Readme.md': 'github/tf-s3-bucket/Readme.md'
      - '<span style="font-style: italic;">Link(GitHub)</span>': 'https://github.com/rbjoergensen/tf-s3-bucket'
    - '<b>tf-workspaces</b>':
      - 'Readme.md': 'github/tf-workspaces/Readme.md'
      - '<span style="font-style: italic;">Link(GitHub)</span>': 'https://github.com/rbjoergensen/tf-workspaces'
