# https://www.mkdocs.org/user-guide/configuration/#documentation-layout
site_name: CallOfTheVoid
site_url: https://docs.callofthevoid.dk
repo_url: https://github.com/rbjoergensen/docs.callofthevoid.dk
edit_uri: ""
extra:
  # Hide the Made with Material for MkDocs notice
  generator: false
  #social:
  #  - icon: fontawesome/brands/linkedin
  #    link: https://www.linkedin.com/in/rasmus-bo-j%C3%B8rgensen-11798168/
# Third-party themes at https://github.com/mkdocs/mkdocs/wiki/MkDocs-Themes
theme: # https://github.com/squidfunk/mkdocs-material
  name: material
  palette:
    accent: pink
    scheme: slate
    primary: teal
  features:
    - toc.integrate
    - navigation.instant
    - navigation.sections
    #- navigation.expand
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
nav:
  - '<b>Introduction</b>': 'index.md'
  - '<b>Articles</b>': 
    - 'Traefik and Docker': 'articles/traefik-setup/article.md'